version: '3.9'

services:
  youtrack:
    image: jetbrains/youtrack:2026.2.17548
    container_name: youtrack
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - youtrack_data:/opt/youtrack/data
      - youtrack_logs:/opt/youtrack/logs
    environment:
      - YOUTRACK_HOME=/opt/youtrack

volumes:
  youtrack_data:
  youtrack_logs:
