import {inject,Injectable} from '@angular/core';
import {AuthService} from '../core/auth.service';
export interface RankingCategory{id:string;user_id:string;name:string;icon:string;color:string;position:number;view_mode:string;show_original_title:boolean;show_author:boolean;show_year:boolean;show_plot:boolean;show_url:boolean;show_image_url:boolean;show_brand:boolean;show_episodes:boolean;show_seasons:boolean;show_nutrition:boolean}
export interface Ranking{id:string;user_id:string;name:string;category_id:string;rating:number;status:string;priority:number;year?:number;description?:string;original_title?:string;creator?:string;url?:string;plot?:string;image_url?:string;brand?:string;episodes?:number;seasons?:number;watched_episodes?:number;nutrition_kcal_100g?:number;nutrition_protein_100g?:number;nutrition_carbs_100g?:number;nutrition_fat_100g?:number;nutrition_fiber_100g?:number;nutrition_salt_100g?:number;consumed_at?:string}
export interface ConsumedDate{id:string;ranking_id:string;consumed_at:string}
@Injectable({providedIn:'root'})export class RankingsService{private auth=inject(AuthService);private client(){if(!this.auth.supabase)throw new Error('Supabase ist nicht konfiguriert.');return this.auth.supabase}private uid(){const id=this.auth.session()?.user.id;if(!id)throw new Error('Bitte zuerst anmelden.');return id}
async load(){const c=this.client(),u=this.uid(),[a,b]=await Promise.all([c.from('ranking_categories').select('*').eq('user_id',u).order('position'),c.from('rankings').select('*').eq('user_id',u)]);if(a.error)throw a.error;if(b.error)throw b.error;const ids=(b.data??[]).map((x:any)=>x.id);let history:ConsumedDate[]=[];if(ids.length){const h=await c.from('ranking_consumed_dates').select('*').in('ranking_id',ids).order('consumed_at',{ascending:false});if(h.error)throw h.error;history=h.data??[]}return{categories:(a.data??[])as RankingCategory[],rankings:(b.data??[])as Ranking[],history}}
async saveCategory(value:Partial<RankingCategory>,id?:string){const data={...value,user_id:this.uid()},r=id?await this.client().from('ranking_categories').update(data).eq('id',id).eq('user_id',this.uid()):await this.client().from('ranking_categories').insert(data);if(r.error)throw r.error}
async removeCategory(id:string){const used=await this.client().from('rankings').select('id').eq('category_id',id).limit(1);if(used.error)throw used.error;if(used.data?.length)throw new Error('Kategorie enthält noch Einträge.');const r=await this.client().from('ranking_categories').delete().eq('id',id).eq('user_id',this.uid());if(r.error)throw r.error}
async saveRanking(value:Partial<Ranking>,id?:string){const data={...value,user_id:this.uid()},r=id?await this.client().from('rankings').update(data).eq('id',id).eq('user_id',this.uid()):await this.client().from('rankings').insert(data);if(r.error)throw r.error}
async removeRanking(id:string){const h=await this.client().from('ranking_consumed_dates').delete().eq('ranking_id',id);if(h.error)throw h.error;const r=await this.client().from('rankings').delete().eq('id',id).eq('user_id',this.uid());if(r.error)throw r.error}
async consume(id:string,date:string){const r=await this.client().from('ranking_consumed_dates').insert({ranking_id:id,consumed_at:date});if(r.error)throw r.error}
}
